# Generated by Django 5.1.4 on 2025-02-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
