# Generated by Django 5.1.4 on 2025-02-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
