# Generated by Django 5.1.4 on 2025-02-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_projects_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.TextField(max_length=25)),
                ('message', models.TextField(max_length=700)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
